version: "3.8"

services:
  postgres:
    container_name: ${APP}-postgres
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  users:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    container_name: ${APP}-users
    restart: always
    env_file:
      - ./users/.env
    ports:
      - "6060:6060"
    depends_on:
      - postgres
    networks:
      - app-network

  messages:
    build:
      context: ./messages
      dockerfile: ./Dockerfile
    container_name: ${APP}-messages
    env_file:
      - .env
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - postgres
      - users
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  # redis:
  #   driver: local
